import { Platform, StyleSheet } from "react-native";
import { colors, monoFont, radius, space, textBase, typeScale } from "../../theme";

export const md = StyleSheet.create({
  blockRoot: { width: "100%", alignSelf: "stretch" },
  block: { marginBottom: space.sm },
  p: {
    ...textBase,
    color: colors.text,
    fontSize: typeScale.body,
    lineHeight: typeScale.bodyLine,
    marginBottom: 6,
  },
  h1: {
    ...textBase,
    color: colors.accent,
    fontSize: 20,
    lineHeight: 28,
    fontWeight: "500",
    marginTop: space.lg,
    marginBottom: space.md,
  },
  h2: {
    ...textBase,
    color: colors.accent,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "500",
    marginTop: space.lg,
    marginBottom: 10,
  },
  h3: {
    ...textBase,
    color: colors.accent,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "500",
    marginTop: space.md,
    marginBottom: space.sm,
  },
  h4: {
    ...textBase,
    color: colors.accent,
    fontSize: typeScale.meta,
    lineHeight: 20,
    fontWeight: "500",
    marginTop: space.md,
    marginBottom: 6,
  },
  h5: {
    ...textBase,
    color: colors.textTertiary,
    fontSize: typeScale.meta,
    lineHeight: 20,
    fontWeight: "400",
    marginTop: 10,
    marginBottom: 6,
  },
  h6: {
    ...textBase,
    color: colors.textTertiary,
    fontSize: typeScale.meta,
    lineHeight: 20,
    fontWeight: "400",
    marginTop: 10,
    marginBottom: 6,
  },
  strong: { fontWeight: "600", color: colors.accent },
  em: { fontStyle: "italic" },
  del: { textDecorationLine: "line-through", color: colors.muted },
  link: { color: colors.alertNote, textDecorationLine: "underline" },
  inlineCode: {
    ...textBase,
    fontFamily: Platform.OS === "web" ? "Menlo" : monoFont,
    backgroundColor: colors.surfaceRaised,
    borderColor: colors.surfaceRaised,
    borderWidth: 1,
    borderRadius: 4,
    color: colors.text,
    fontSize: 14,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  codeBlock: {
    backgroundColor: colors.surfaceRaised,
    borderColor: colors.surfaceRaised,
    borderWidth: 1,
    borderRadius: radius.sm,
    padding: space.lg,
    marginVertical: space.sm,
    maxHeight: 320,
  },
  codeText: {
    ...textBase,
    fontFamily: Platform.OS === "web" ? "Menlo" : monoFont,
    color: colors.text,
    fontSize: 13,
    lineHeight: 20,
  },
  list: { marginVertical: space.sm, paddingLeft: 8 },
  li: { flexDirection: "row", alignItems: "flex-start", paddingVertical: 2 },
  liMark: {
    ...textBase,
    color: colors.text,
    fontSize: typeScale.body,
    lineHeight: typeScale.bodyLine,
    width: 22,
  },
  liBody: { flex: 1, minWidth: 0 },
  quote: {
    borderLeftColor: colors.border,
    borderLeftWidth: 4,
    paddingLeft: space.md,
    marginVertical: space.sm,
  },
  quoteText: {
    ...textBase,
    color: colors.muted,
    fontSize: typeScale.body,
    lineHeight: typeScale.bodyLine,
    fontStyle: "italic",
  },
  hr: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: space.lg,
  },
  tableScroll: { marginVertical: space.lg },
  table: {
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.lg,
    overflow: "hidden",
    flexDirection: "column",
    alignSelf: "flex-start",
  },
  tr: { flexDirection: "row", alignItems: "stretch" },
  th: {
    backgroundColor: colors.surface,
    borderRightColor: colors.border,
    borderRightWidth: 1,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    paddingHorizontal: space.md,
    paddingVertical: space.sm,
    flexGrow: 0,
    flexShrink: 0,
  },
  td: {
    borderRightColor: colors.border,
    borderRightWidth: 1,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    paddingHorizontal: space.md,
    paddingVertical: space.sm,
    flexGrow: 0,
    flexShrink: 0,
  },
  thText: {
    ...textBase,
    color: "#ffffff",
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "600",
  },
  tdText: {
    ...textBase,
    color: colors.text,
    fontSize: 14,
    lineHeight: 20,
  },
  image: {
    width: "100%",
    height: 180,
    borderRadius: radius.md,
    marginVertical: space.sm,
    backgroundColor: colors.surface,
  },
  alert: {
    borderLeftWidth: 4,
    borderRadius: 2,
    paddingHorizontal: space.md,
    paddingVertical: space.sm,
    marginVertical: space.md,
  },
  alertTitle: {
    ...textBase,
    fontWeight: "600",
    fontSize: typeScale.meta,
    marginBottom: 4,
  },
});
